export const leetcodeQuestions = [
    { title: "Two Sum", url: "https://leetcode.com/problems/two-sum/", difficulty: "Super Easy" },
    { title: "Palindrome Number", url: "https://leetcode.com/problems/palindrome-number/", difficulty: "Super Easy" },
    { title: "Roman to Integer", url: "https://leetcode.com/problems/roman-to-integer/", difficulty: "Easy" },
    { title: "Longest Common Prefix", url: "https://leetcode.com/problems/longest-common-prefix/", difficulty: "Easy" },
    { title: "Valid Parentheses", url: "https://leetcode.com/problems/valid-parentheses/", difficulty: "Easy" },
    { title: "Merge Two Sorted Lists", url: "https://leetcode.com/problems/merge-two-sorted-lists/", difficulty: "Easy" },
    { title: "Remove Duplicates from Sorted Array", url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/", difficulty: "Super Easy" },
    { title: "Remove Element", url: "https://leetcode.com/problems/remove-element/", difficulty: "Super Easy" },
    { title: "Find the Index of the First Occurrence in a String", url: "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/", difficulty: "Easy" },
    { title: "Search Insert Position", url: "https://leetcode.com/problems/search-insert-position/", difficulty: "Easy" },
    { title: "Length of Last Word", url: "https://leetcode.com/problems/length-of-last-word/", difficulty: "Super Easy" },
    { title: "Plus One", url: "https://leetcode.com/problems/plus-one/", difficulty: "Super Easy" },
    { title: "Add Binary", url: "https://leetcode.com/problems/add-binary/", difficulty: "Easy" },
    { title: "Sqrt(x)", url: "https://leetcode.com/problems/sqrtx/", difficulty: "Easy" },
    { title: "Climbing Stairs", url: "https://leetcode.com/problems/climbing-stairs/", difficulty: "Easy" },
    { title: "Merge Sorted Array", url: "https://leetcode.com/problems/merge-sorted-array/", difficulty: "Easy" },
    { title: "Binary Tree Inorder Traversal", url: "https://leetcode.com/problems/binary-tree-inorder-traversal/", difficulty: "Easy" },
    { title: "Same Tree", url: "https://leetcode.com/problems/same-tree/", difficulty: "Easy" },
    { title: "Symmetric Tree", url: "https://leetcode.com/problems/symmetric-tree/", difficulty: "Easy" },
    { title: "Maximum Depth of Binary Tree", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", difficulty: "Easy" },
    { title: "Convert Sorted Array to Binary Search Tree", url: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/", difficulty: "Easy" },
    { title: "Balanced Binary Tree", url: "https://leetcode.com/problems/balanced-binary-tree/", difficulty: "Easy" },
    { title: "Minimum Depth of Binary Tree", url: "https://leetcode.com/problems/minimum-depth-of-binary-tree/", difficulty: "Easy" },
    { title: "Path Sum", url: "https://leetcode.com/problems/path-sum/", difficulty: "Easy" },
    { title: "Pascal's Triangle", url: "https://leetcode.com/problems/pascals-triangle/", difficulty: "Super Easy" },
    { title: "Best Time to Buy and Sell Stock", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", difficulty: "Easy" },
    { title: "Valid Palindrome", url: "https://leetcode.com/problems/valid-palindrome/", difficulty: "Super Easy" },
    { title: "Single Number", url: "https://leetcode.com/problems/single-number/", difficulty: "Super Easy" },
    { title: "Linked List Cycle", url: "https://leetcode.com/problems/linked-list-cycle/", difficulty: "Easy" },
    { title: "Intersection of Two Linked Lists", url: "https://leetcode.com/problems/intersection-of-two-linked-lists/", difficulty: "Easy" },
    { title: "Excel Sheet Column Title", url: "https://leetcode.com/problems/excel-sheet-column-title/", difficulty: "Easy" },
    { title: "Majority Element", url: "https://leetcode.com/problems/majority-element/", difficulty: "Super Easy" },
    { title: "Excel Sheet Column Number", url: "https://leetcode.com/problems/excel-sheet-column-number/", difficulty: "Easy" },
    { title: "Reverse Bits", url: "https://leetcode.com/problems/reverse-bits/", difficulty: "Easy" },
    { title: "Number of 1 Bits", url: "https://leetcode.com/problems/number-of-1-bits/", difficulty: "Super Easy" },
    { title: "Happy Number", url: "https://leetcode.com/problems/happy-number/", difficulty: "Easy" },
    { title: "Remove Linked List Elements", url: "https://leetcode.com/problems/remove-linked-list-elements/", difficulty: "Easy" },
    { title: "Isomorphic Strings", url: "https://leetcode.com/problems/isomorphic-strings/", difficulty: "Easy" },
    { title: "Reverse Linked List", url: "https://leetcode.com/problems/reverse-linked-list/", difficulty: "Easy" },
    { title: "Contains Duplicate", url: "https://leetcode.com/problems/contains-duplicate/", difficulty: "Super Easy" },
    { title: "Contains Duplicate II", url: "https://leetcode.com/problems/contains-duplicate-ii/", difficulty: "Easy" },
    { title: "Implement Stack using Queues", url: "https://leetcode.com/problems/implement-stack-using-queues/", difficulty: "Easy" },
    { title: "Invert Binary Tree", url: "https://leetcode.com/problems/invert-binary-tree/", difficulty: "Super Easy" },
    { title: "Power of Two", url: "https://leetcode.com/problems/power-of-two/", difficulty: "Super Easy" },
    { title: "Implement Queue using Stacks", url: "https://leetcode.com/problems/implement-queue-using-stacks/", difficulty: "Easy" },
    { title: "Palindrome Linked List", url: "https://leetcode.com/problems/palindrome-linked-list/", difficulty: "Easy" },
    { title: "Valid Anagram", url: "https://leetcode.com/problems/valid-anagram/", difficulty: "Super Easy" },
    { title: "Missing Number", url: "https://leetcode.com/problems/missing-number/", difficulty: "Super Easy" },
    { title: "First Bad Version", url: "https://leetcode.com/problems/first-bad-version/", difficulty: "Easy" },
    { title: "Move Zeroes", url: "https://leetcode.com/problems/move-zeroes/", difficulty: "Super Easy" },
    { title: "Word Pattern", url: "https://leetcode.com/problems/word-pattern/", difficulty: "Easy" },
    { title: "Nim Game", url: "https://leetcode.com/problems/nim-game/", difficulty: "Super Easy" },
    { title: "Power of Three", url: "https://leetcode.com/problems/power-of-three/", difficulty: "Super Easy" },
    { title: "Reverse String", url: "https://leetcode.com/problems/reverse-string/", difficulty: "Super Easy" },
    { title: "Reverse Vowels of a String", url: "https://leetcode.com/problems/reverse-vowels-of-a-string/", difficulty: "Easy" },
    { title: "Intersection of Two Arrays", url: "https://leetcode.com/problems/intersection-of-two-arrays/", difficulty: "Super Easy" },
    { title: "Valid Perfect Square", url: "https://leetcode.com/problems/valid-perfect-square/", difficulty: "Super Easy" },
    { title: "Sum of Two Integers", url: "https://leetcode.com/problems/sum-of-two-integers/", difficulty: "Easy" },
    { title: "Find the Difference", url: "https://leetcode.com/problems/find-the-difference/", difficulty: "Easy" },
    { title: "Is Subsequence", url: "https://leetcode.com/problems/is-subsequence/", difficulty: "Easy" },
    { title: "Ransom Note", url: "https://leetcode.com/problems/ransom-note/", difficulty: "Easy" }
];
